name: Build APK

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Resolve o aviso do Node.js 20 e força o uso do Node 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Pegar o código
        uses: actions/checkout@v4

      - name: Instalar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependências de Compilação
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y libgtk-3-dev libblkid-dev liblzma-dev

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Aceitar Licenças do Android (Crítico)
        run: |
          yes | sdkmanager --licenses || true

      - name: Instalar Flet e Gerar APK
        run: |
          pip install flet
          # O comando 'flet build apk' as vezes precisa rodar em modo headless no CI
          flet build apk --verbose

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: BeybladeApp-APK
          path: build/apk/*.apk
